apiVersion: 1

datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false

    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-2s"
        spanEndTimeShift: "2s"
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: '{service_name="mock-inference"} | json | trace_id="$${__trace.traceId}"'